[2019-06-30 03:21:03,688]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 03:33:18,753]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 03:33:23,754]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 03:33:28,754]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:02:06,100]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:02:06,101]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:02:06,216]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:02:06,218]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:02:06,219]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:02:06,321]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:02:06,321]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:02:06,322]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=103ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:02:56,224]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:02:56,224]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:02:56,225]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:02:56,225]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:02:56,227]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:02:56,231]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:02:56,231]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:02:56,231]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=4ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:03:26,230]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:03:26,231]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:03:26,231]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:03:26,231]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:03:26,232]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:03:26,235]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:03:26,235]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:03:26,235]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=3ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:04:28,872]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:04:28,873]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:04:29,094]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:04:29,116]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:04:29,122]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:04:29,303]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:04:29,303]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:04:29,304]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=181ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:05:08,924]   INFO -     jetbrains.buildServer.LDAP - Incomplete LDAP configuration: teamcity.users.login.filter property is not defined in the LDAP configuration. Attempting to proceed with 'devops' as LDAP user and TeamCity username.
[2019-06-30 04:05:08,928]   WARN -     jetbrains.buildServer.LDAP - LDAP bind operation returned an error while performing LDAP bind for user 'example\devops'. LDAP server says: Invalid DN syntax. Original error: javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:07:29,333]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:07:29,335]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:07:29,335]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:07:29,336]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:07:29,337]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:07:29,342]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:07:29,342]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:07:29,342]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=5ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Invalid DN syntax. Original error: org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:07:43,692]   INFO -     jetbrains.buildServer.LDAP - Incomplete LDAP configuration: teamcity.users.login.filter property is not defined in the LDAP configuration. Attempting to proceed with 'devops' as LDAP user and TeamCity username.
[2019-06-30 04:07:43,695]   WARN -     jetbrains.buildServer.LDAP - LDAP bind operation returned an error while performing LDAP bind for user 'devops'. LDAP server says: Invalid DN syntax. Original error: javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:11:19,351]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:11:19,352]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:11:19,352]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:11:19,353]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:11:19,353]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:11:19,362]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
[2019-06-30 04:11:19,362]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:11:19,363]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=10ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:12:34,997]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:12:35,000]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:12:35,447]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:12:35,455]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:12:35,466]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:12:35,654]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
[2019-06-30 04:12:35,655]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:12:35,661]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=195ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:13:22,778]   WARN -     jetbrains.buildServer.LDAP - LDAP search operation returned an error while searching for user entry by 'devops' to perform bind. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
[2019-06-30 04:16:01,880]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:16:01,882]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:16:01,882]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:16:01,883]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:16:01,884]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:16:01,888]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,OU=TD,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
[2019-06-30 04:16:01,888]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:16:01,888]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=4ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,OU=TD,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:17:03,040]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:17:03,043]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:17:03,156]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:17:03,158]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:17:03,178]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:17:03,360]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,OU=TD,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
[2019-06-30 04:17:03,360]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:17:03,361]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=183ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,OU=TD,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:17:25,707]   WARN -     jetbrains.buildServer.LDAP - LDAP search operation returned an error while searching for user entry by 'devops' to perform bind. While initializing LDAP connection. Wrong credentials specified in the LDAP configuration? Check 'java.naming.security.principal' property (current value: 'CN=Dev,OU=TD,DC=example,DC=org', full DN is recommended) and 'java.naming.security.credentials' property. Set them to empty values to use anonumous LDAP access. Original error: org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
[2019-06-30 04:18:24,050]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:18:24,050]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:18:24,051]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:18:24,051]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:18:24,052]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:18:24,056]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]
[2019-06-30 04:18:24,056]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:18:24,056]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=4ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:19:09,055]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:19:09,056]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:19:09,057]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:19:09,057]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:19:09,058]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:19:09,062]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]
[2019-06-30 04:19:09,062]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:19:09,062]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=4ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:21:23,856]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:21:23,857]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:21:23,938]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:21:23,945]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:21:23,953]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:21:24,091]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]
[2019-06-30 04:21:24,091]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:21:24,092]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=138ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:22:02,072]   WARN -     jetbrains.buildServer.LDAP - LDAP search operation returned an error while searching for user entry by 'devops' to perform bind. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]
[2019-06-30 04:24:36,016]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:24:36,018]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:24:36,021]   INFO -     jetbrains.buildServer.LDAP - LDAP synchronization is set to inactive: jetbrains.buildServer.serverSide.ldap.LdapIncorrectConfigurationException: Error in LDAP configuration: mandatory properties 'java.naming.security.credentials', 'java.naming.security.principal' are not defined.
[2019-06-30 04:25:43,556]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:25:43,568]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:25:43,585]   INFO -     jetbrains.buildServer.LDAP - LDAP synchronization is set to inactive: jetbrains.buildServer.serverSide.ldap.LdapIncorrectConfigurationException: Error in LDAP configuration: mandatory properties 'java.naming.security.credentials', 'java.naming.security.principal' are not defined.
[2019-06-30 04:26:22,269]   WARN -     jetbrains.buildServer.LDAP - Cannot retrieve the username to perform LDAP search. Error in LDAP configuration: mandatory properties 'java.naming.security.credentials', 'java.naming.security.principal' are not defined.
[2019-06-30 04:26:58,555]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:26:58,555]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:26:58,622]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:26:58,623]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:26:58,625]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:26:58,689]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]
[2019-06-30 04:26:58,689]   WARN -     jetbrains.buildServer.LDAP - Skipping groups synchronization as user synchronization failed with an error
[2019-06-30 04:26:58,690]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=false, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=65ms, errors=2, errors: [Error while retrieving LDAP users, skipping users synchronization: LDAP search operation returned an error while retrieving users. While initializing LDAP connection. LDAP server says: Unwilling to perform. Original error: org.springframework.ldap.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - unauthenticated bind (DN with no password) disallowed], Skipping groups synchronization as user synchronization failed with an error]
[2019-06-30 04:39:43,672]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:39:43,673]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:39:43,674]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:39:43,674]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:39:43,675]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:39:43,774]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 04:39:43,779]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 04:39:43,788]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 04:39:43,789]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=113ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 04:40:41,520]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:40:41,531]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:40:41,790]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:40:41,807]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:40:41,816]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:40:42,291]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 04:40:42,321]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 04:40:43,323]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 04:40:43,323]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=1s,507ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 04:41:23,446]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'devops' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(sAMAccountName=devops)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 04:43:08,354]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'devops' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(sAMAccountName=devops)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 04:44:54,138]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:44:54,139]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:44:54,139]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:44:54,141]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:44:54,141]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:44:54,148]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 04:44:54,149]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 04:44:54,149]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 04:44:54,150]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=9ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 04:45:50,508]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 04:45:50,514]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:45:50,609]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:45:50,625]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:45:50,636]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:45:50,894]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 04:45:50,903]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 04:45:51,508]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 04:45:51,509]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=873ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 04:46:25,102]   INFO -     jetbrains.buildServer.LDAP - Incomplete LDAP configuration: teamcity.users.login.filter property is not defined in the LDAP configuration. Attempting to proceed with 'devops' as LDAP user and TeamCity username.
[2019-06-30 04:46:25,107]   WARN -     jetbrains.buildServer.LDAP - LDAP bind operation returned an error while performing LDAP bind for user 'devops'. LDAP server says: Invalid DN syntax. Original error: javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
[2019-06-30 04:46:53,931]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 04:46:53,933]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 04:46:53,934]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 04:46:53,941]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 04:46:53,941]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 04:46:53,944]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 04:46:53,945]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 04:46:53,945]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 04:46:53,945]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=4ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 05:46:53,941]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 05:46:53,948]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 05:46:53,953]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 05:46:53,954]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 05:46:54,012]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 05:46:54,012]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=64ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 06:46:53,941]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 06:46:53,941]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 06:46:53,949]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=user)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 06:46:53,949]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 06:46:53,979]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 06:46:53,980]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=38ms, errors=2, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-06-30 08:16:42,314]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 08:16:42,328]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 08:16:42,909]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 08:16:42,923]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 08:16:42,938]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 08:16:44,570]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=inetOrgPerson)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:16:44,584]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 08:16:44,599]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=1s,661ms, errors=1, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist]
[2019-06-30 08:17:21,174]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'admin' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(sAMAccountName=admin)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 08:17:24,299]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'admin' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(sAMAccountName=admin)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 08:18:47,743]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'devops' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(sAMAccountName=devops)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 08:19:58,404]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties
[2019-06-30 08:19:58,404]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 08:19:58,404]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 08:19:58,404]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 08:19:58,404]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 08:19:58,407]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=inetOrgPerson)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:19:58,408]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 08:19:58,409]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=5ms, errors=1, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist]
[2019-06-30 08:21:01,051]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 08:21:01,053]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 08:21:01,140]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 08:21:01,141]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 08:21:01,144]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 08:21:01,651]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(objectClass=inetOrgPerson)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:21:01,655]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 08:21:01,690]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=545ms, errors=1, errors: [Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist]
[2019-06-30 08:21:33,818]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'devops' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(uid=devops)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 08:21:55,872]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'devops' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(uid=devops)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 08:22:05,119]   INFO -     jetbrains.buildServer.LDAP - Login attempt failed: No LDAP entry found by 'devops' when searching for user entry to perform bind. Wrong username? Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(uid=devops)' (set by 'teamcity.users.login.filter' property)
[2019-06-30 08:23:46,267]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(&(objectClass=inetOrgPerson)(sAMAccountName=devops))', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:23:46,269]   WARN -     jetbrains.buildServer.LDAP - Error retrieving LDAP details for user 'devops' {id=1}: Failed to get user data from LDAP (search result is empty) for user 'devops' {id=1}. Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(&(objectClass=inetOrgPerson)(sAMAccountName=devops))'
[2019-06-30 08:23:46,269]   WARN -     jetbrains.buildServer.LDAP - No remote data found for user 'devops' {id=1}
[2019-06-30 08:23:47,124]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(&(objectClass=inetOrgPerson)(sAMAccountName=devops))', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:23:47,124]   WARN -     jetbrains.buildServer.LDAP - Error retrieving LDAP details for user 'devops' {id=1}: Failed to get user data from LDAP (search result is empty) for user 'devops' {id=1}. Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(&(objectClass=inetOrgPerson)(sAMAccountName=devops))'
[2019-06-30 08:23:47,124]   WARN -     jetbrains.buildServer.LDAP - No remote data found for user 'devops' {id=1}
[2019-06-30 08:58:09,443]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-06-30 08:58:09,445]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-06-30 08:58:09,631]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-06-30 08:58:09,638]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 08:58:09,644]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 08:58:09,911]   INFO -     jetbrains.buildServer.LDAP - Found 1 search results for search base='', filter='(objectClass=inetOrgPerson)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:58:10,450]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP user information: LDAP error retrieving attribute 'sAMAccountName' (set by teamcity.users.username property) from LDAP entry cn=adiluck chooprateep,ou=users: null:null:No attributes: no attribute
[2019-06-30 08:58:10,451]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 08:58:19,262]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=9s,617ms, errors=2, errors: [Error while retrieving LDAP user information: LDAP error retrieving attribute 'sAMAccountName' (set by teamcity.users.username property) from LDAP entry cn=adiluck chooprateep,ou=users: null:null:No attributes: no attribute, Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist]
[2019-06-30 08:59:04,032]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(&(objectClass=inetOrgPerson)(sAMAccountName=devops))', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:59:04,033]   WARN -     jetbrains.buildServer.LDAP - Error retrieving LDAP details for user 'devops' {id=1}: Failed to get user data from LDAP (search result is empty) for user 'devops' {id=1}. Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(&(objectClass=inetOrgPerson)(sAMAccountName=devops))'
[2019-06-30 08:59:04,034]   WARN -     jetbrains.buildServer.LDAP - No remote data found for user 'devops' {id=1}
[2019-06-30 08:59:04,412]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(&(objectClass=inetOrgPerson)(sAMAccountName=devops))', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 08:59:04,413]   WARN -     jetbrains.buildServer.LDAP - Error retrieving LDAP details for user 'devops' {id=1}: Failed to get user data from LDAP (search result is empty) for user 'devops' {id=1}. Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(&(objectClass=inetOrgPerson)(sAMAccountName=devops))'
[2019-06-30 08:59:04,413]   WARN -     jetbrains.buildServer.LDAP - No remote data found for user 'devops' {id=1}
[2019-06-30 09:58:09,632]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-06-30 09:58:09,632]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-06-30 09:58:09,788]   INFO -     jetbrains.buildServer.LDAP - Found 1 search results for search base='', filter='(objectClass=inetOrgPerson)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-06-30 09:58:09,789]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP user information: LDAP error retrieving attribute 'sAMAccountName' (set by teamcity.users.username property) from LDAP entry cn=adiluck chooprateep,ou=users: null:null:No attributes: no attribute
[2019-06-30 09:58:09,790]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-06-30 09:58:09,799]   WARN -     jetbrains.buildServer.LDAP - jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users
[2019-06-30 09:58:09,799]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=167ms, errors=3, errors: [Error while retrieving LDAP user information: LDAP error retrieving attribute 'sAMAccountName' (set by teamcity.users.username property) from LDAP entry cn=adiluck chooprateep,ou=users: null:null:No attributes: no attribute, Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist, jetbrains.buildServer.users.sync.SyncFailedException: TeamCity refuses to delete all users]
[2019-07-01 06:55:54,813]   INFO -     jetbrains.buildServer.LDAP - ------ LdapManager Start ------
[2019-07-01 06:55:55,142]   INFO -     jetbrains.buildServer.LDAP - Reloading LDAP properties (sync)
[2019-07-01 06:55:55,908]   INFO -     jetbrains.buildServer.LDAP - LDAP properties loaded
[2019-07-01 06:55:55,912]   INFO -     jetbrains.buildServer.LDAP - Starting synchronization session
[2019-07-01 06:55:55,924]   INFO -     jetbrains.buildServer.LDAP - Fetching remote users and groups
[2019-07-01 06:55:58,351]   INFO -     jetbrains.buildServer.LDAP - Found 1 search results for search base='', filter='(objectClass=inetOrgPerson)', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-07-01 06:55:58,370]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP user information: LDAP error retrieving attribute 'sAMAccountName' (set by teamcity.users.username property) from LDAP entry cn=adiluck chooprateep,ou=users: null:null:No attributes: no attribute
[2019-07-01 06:55:58,379]   WARN -     jetbrains.buildServer.LDAP - Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist
[2019-07-01 06:55:58,539]   INFO -     jetbrains.buildServer.LDAP - Last synchronization statistics: user sync enabled=true, created users=0, updated users=0, deleted users=0, remote users=0, matched users=0, group sync enabled=false, created groups=0, updated groups=0, deleted groups=0, remote groups=0, matched groups=0, duration=2s,615ms, errors=2, errors: [Error while retrieving LDAP user information: LDAP error retrieving attribute 'sAMAccountName' (set by teamcity.users.username property) from LDAP entry cn=adiluck chooprateep,ou=users: null:null:No attributes: no attribute, Error while retrieving LDAP groups, skipping groups synchronization: LDAP operation returned an error while retrieving groups mapping. Groups mapping file '/data/teamcity_server/datadir/config/ldap-mapping.xml' does not exist]
[2019-07-01 06:58:27,123]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(&(objectClass=inetOrgPerson)(sAMAccountName=devops))', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-07-01 06:58:28,293]   WARN -     jetbrains.buildServer.LDAP - Error retrieving LDAP details for user 'devops' {id=1}: Failed to get user data from LDAP (search result is empty) for user 'devops' {id=1}. Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(&(objectClass=inetOrgPerson)(sAMAccountName=devops))'
[2019-07-01 06:58:28,300]   WARN -     jetbrains.buildServer.LDAP - No remote data found for user 'devops' {id=1}
[2019-07-01 06:58:30,509]   INFO -     jetbrains.buildServer.LDAP - Found 0 search results for search base='', filter='(&(objectClass=inetOrgPerson)(sAMAccountName=devops))', scope=2, attributes=[mail, sAMAccountName, displayName, member, distinguishedName]
[2019-07-01 06:58:30,511]   WARN -     jetbrains.buildServer.LDAP - Error retrieving LDAP details for user 'devops' {id=1}: Failed to get user data from LDAP (search result is empty) for user 'devops' {id=1}. Used root URL: 'ldap://10.11.1.2:389/DC=example,DC=org' (set by 'java.naming.provider.url' property) 
Used search base: '' (set by 'teamcity.users.base' property, should be relative to the value of 'java.naming.provider.url') 
Used search filter: '(&(objectClass=inetOrgPerson)(sAMAccountName=devops))'
[2019-07-01 06:58:30,512]   WARN -     jetbrains.buildServer.LDAP - No remote data found for user 'devops' {id=1}
